const cropRecommendationDataset = {
  "andhra pradesh": [
    {
      district: "Tirupati",
      bestCrop: "Groundnut",
      topCrop1: "Groundnut",
      topCrop2: "Mango",
      topCrop3: "Tomato",
      expectedYield: "28 Q/acre",
      marketPrice: "₹6,800/Q",
      profitPerAcre: "₹95,000/acre",
      riskLevel: "Low",
      reason: "Suitable red soil, strong rainfall, and good market demand.",
    },
    {
      district: "Anantapur",
      bestCrop: "Groundnut",
      topCrop1: "Groundnut",
      topCrop2: "Sunflower",
      topCrop3: "Cotton",
      expectedYield: "27 Q/acre",
      marketPrice: "₹6,700/Q",
      profitPerAcre: "₹92,000/acre",
      riskLevel: "Low",
      reason: "Well-suited for dryland conditions and stable demand.",
    },
    {
      district: "Vijayawada",
      bestCrop: "Paddy",
      topCrop1: "Paddy",
      topCrop2: "Cotton",
      topCrop3: "Groundnut",
      expectedYield: "52 Q/acre",
      marketPrice: "₹2,400/Q",
      profitPerAcre: "₹84,000/acre",
      riskLevel: "Low",
      reason: "Ideal irrigation conditions and strong delta-region demand.",
    },
    {
      district: "Guntur",
      bestCrop: "Cotton",
      topCrop1: "Cotton",
      topCrop2: "Groundnut",
      topCrop3: "Paddy",
      expectedYield: "29 Q/acre",
      marketPrice: "₹6,900/Q",
      profitPerAcre: "₹87,000/acre",
      riskLevel: "Medium",
      reason: "Good climate support and strong fiber market demand.",
    },
    {
      district: "Visakhapatnam",
      bestCrop: "Mango",
      topCrop1: "Mango",
      topCrop2: "Groundnut",
      topCrop3: "Tomato",
      expectedYield: "18 Q/acre",
      marketPrice: "₹5,200/Q",
      profitPerAcre: "₹90,000/acre",
      riskLevel: "Low",
      reason: "Coastal climate and strong horticulture demand support this crop.",
    },
    {
      district: "default",
      bestCrop: "Groundnut",
      topCrop1: "Groundnut",
      topCrop2: "Mango",
      topCrop3: "Cotton",
      expectedYield: "28 Q/acre",
      marketPrice: "₹6,800/Q",
      profitPerAcre: "₹95,000/acre",
      riskLevel: "Low",
      reason: "State-level fallback recommendation for Andhra Pradesh.",
    },
  ],
  "telangana": [
    {
      district: "Hyderabad",
      bestCrop: "Cotton",
      topCrop1: "Cotton",
      topCrop2: "Maize",
      topCrop3: "Red Gram",
      expectedYield: "30 Q/acre",
      marketPrice: "₹7,100/Q",
      profitPerAcre: "₹88,000/acre",
      riskLevel: "Medium",
      reason: "Favorable climate and strong market demand for cotton.",
    },
    {
      district: "Warangal",
      bestCrop: "Red Gram",
      topCrop1: "Red Gram",
      topCrop2: "Cotton",
      topCrop3: "Maize",
      expectedYield: "16 Q/acre",
      marketPrice: "₹6,200/Q",
      profitPerAcre: "₹76,000/acre",
      riskLevel: "Low",
      reason: "Dryland-friendly and suitable for local soil conditions.",
    },
    {
      district: "Karimnagar",
      bestCrop: "Maize",
      topCrop1: "Maize",
      topCrop2: "Cotton",
      topCrop3: "Red Gram",
      expectedYield: "34 Q/acre",
      marketPrice: "₹2,200/Q",
      profitPerAcre: "₹72,000/acre",
      riskLevel: "Low",
      reason: "Reliable yields and strong demand for feed-grade maize.",
    },
    {
      district: "Nizamabad",
      bestCrop: "Sugarcane",
      topCrop1: "Sugarcane",
      topCrop2: "Cotton",
      topCrop3: "Maize",
      expectedYield: "400 Q/acre",
      marketPrice: "₹320/Q",
      profitPerAcre: "₹1,10,000/acre",
      riskLevel: "Medium",
      reason: "Good water access and strong industrial demand support this crop.",
    },
    {
      district: "default",
      bestCrop: "Cotton",
      topCrop1: "Cotton",
      topCrop2: "Maize",
      topCrop3: "Red Gram",
      expectedYield: "30 Q/acre",
      marketPrice: "₹7,100/Q",
      profitPerAcre: "₹88,000/acre",
      riskLevel: "Medium",
      reason: "State-level fallback recommendation for Telangana.",
    },
  ],
  "tamil nadu": [
    {
      district: "Coimbatore",
      bestCrop: "Sugarcane",
      topCrop1: "Sugarcane",
      topCrop2: "Coconut",
      topCrop3: "Banana",
      expectedYield: "420 Q/acre",
      marketPrice: "₹340/Q",
      profitPerAcre: "₹1,15,000/acre",
      riskLevel: "Low",
      reason: "High water availability and strong industrial demand.",
    },
    {
      district: "Thanjavur",
      bestCrop: "Paddy",
      topCrop1: "Paddy",
      topCrop2: "Banana",
      topCrop3: "Sugarcane",
      expectedYield: "55 Q/acre",
      marketPrice: "₹2,300/Q",
      profitPerAcre: "₹82,000/acre",
      riskLevel: "Low",
      reason: "Ideal wetland conditions and strong paddy market demand.",
    },
    {
      district: "Madurai",
      bestCrop: "Banana",
      topCrop1: "Banana",
      topCrop2: "Sugarcane",
      topCrop3: "Cotton",
      expectedYield: "320 Q/acre",
      marketPrice: "₹35/Q",
      profitPerAcre: "₹86,000/acre",
      riskLevel: "Medium",
      reason: "Favorable temperature and strong local demand for fruit crops.",
    },
    {
      district: "Erode",
      bestCrop: "Cotton",
      topCrop1: "Cotton",
      topCrop2: "Banana",
      topCrop3: "Sugarcane",
      expectedYield: "28 Q/acre",
      marketPrice: "₹6,600/Q",
      profitPerAcre: "₹84,000/acre",
      riskLevel: "Low",
      reason: "Well-suited for the district's climate and textile demand.",
    },
    {
      district: "default",
      bestCrop: "Sugarcane",
      topCrop1: "Sugarcane",
      topCrop2: "Coconut",
      topCrop3: "Banana",
      expectedYield: "420 Q/acre",
      marketPrice: "₹340/Q",
      profitPerAcre: "₹1,15,000/acre",
      riskLevel: "Low",
      reason: "State-level fallback recommendation for Tamil Nadu.",
    },
  ],
  karnataka: [
    {
      district: "Mysuru",
      bestCrop: "Ragi",
      topCrop1: "Ragi",
      topCrop2: "Maize",
      topCrop3: "Sugarcane",
      expectedYield: "24 Q/acre",
      marketPrice: "₹3,800/Q",
      profitPerAcre: "₹75,000/acre",
      riskLevel: "Low",
      reason: "Suitable for the region's rainfall pattern and local demand.",
    },
    {
      district: "Belagavi",
      bestCrop: "Sugarcane",
      topCrop1: "Sugarcane",
      topCrop2: "Cotton",
      topCrop3: "Maize",
      expectedYield: "410 Q/acre",
      marketPrice: "₹335/Q",
      profitPerAcre: "₹1,12,000/acre",
      riskLevel: "Low",
      reason: "Excellent climate and strong regional demand.",
    },
    {
      district: "Dharwad",
      bestCrop: "Maize",
      topCrop1: "Maize",
      topCrop2: "Cotton",
      topCrop3: "Ragi",
      expectedYield: "33 Q/acre",
      marketPrice: "₹2,100/Q",
      profitPerAcre: "₹70,000/acre",
      riskLevel: "Medium",
      reason: "Well-suited for dryland conditions and feed demand.",
    },
    {
      district: "Shivamogga",
      bestCrop: "Arecanut",
      topCrop1: "Arecanut",
      topCrop2: "Coffee",
      topCrop3: "Ragi",
      expectedYield: "15 Q/acre",
      marketPrice: "₹1,200/Q",
      profitPerAcre: "₹96,000/acre",
      riskLevel: "Low",
      reason: "High-value plantation crop with strong regional demand.",
    },
    {
      district: "default",
      bestCrop: "Maize",
      topCrop1: "Maize",
      topCrop2: "Cotton",
      topCrop3: "Ragi",
      expectedYield: "33 Q/acre",
      marketPrice: "₹2,100/Q",
      profitPerAcre: "₹70,000/acre",
      riskLevel: "Medium",
      reason: "State-level fallback recommendation for Karnataka.",
    },
  ],
  kerala: [
    {
      district: "Thiruvananthapuram",
      bestCrop: "Coconut",
      topCrop1: "Coconut",
      topCrop2: "Rubber",
      topCrop3: "Banana",
      expectedYield: "90 nuts/tree",
      marketPrice: "₹25/nut",
      profitPerAcre: "₹78,000/acre",
      riskLevel: "Low",
      reason: "Excellent climatic fit and robust plantation demand.",
    },
    {
      district: "Kochi",
      bestCrop: "Coconut",
      topCrop1: "Coconut",
      topCrop2: "Banana",
      topCrop3: "Rubber",
      expectedYield: "88 nuts/tree",
      marketPrice: "₹24/nut",
      profitPerAcre: "₹76,000/acre",
      riskLevel: "Low",
      reason: "Strong plantation suitability and steady demand.",
    },
    {
      district: "default",
      bestCrop: "Coconut",
      topCrop1: "Coconut",
      topCrop2: "Rubber",
      topCrop3: "Banana",
      expectedYield: "90 nuts/tree",
      marketPrice: "₹25/nut",
      profitPerAcre: "₹78,000/acre",
      riskLevel: "Low",
      reason: "State-level fallback recommendation for Kerala.",
    },
  ],
  maharashtra: [
    {
      district: "Nashik",
      bestCrop: "Cotton",
      topCrop1: "Cotton",
      topCrop2: "Sugarcane",
      topCrop3: "Soybean",
      expectedYield: "28 Q/acre",
      marketPrice: "₹6,900/Q",
      profitPerAcre: "₹84,000/acre",
      riskLevel: "Medium",
      reason: "Balanced rainfall and strong market demand support cotton.",
    },
    {
      district: "Pune",
      bestCrop: "Sugarcane",
      topCrop1: "Sugarcane",
      topCrop2: "Cotton",
      topCrop3: "Soybean",
      expectedYield: "400 Q/acre",
      marketPrice: "₹320/Q",
      profitPerAcre: "₹1,08,000/acre",
      riskLevel: "Medium",
      reason: "Good irrigation support and steady industrial demand.",
    },
    {
      district: "default",
      bestCrop: "Cotton",
      topCrop1: "Cotton",
      topCrop2: "Sugarcane",
      topCrop3: "Soybean",
      expectedYield: "28 Q/acre",
      marketPrice: "₹6,900/Q",
      profitPerAcre: "₹84,000/acre",
      riskLevel: "Medium",
      reason: "State-level fallback recommendation for Maharashtra.",
    },
  ],
  punjab: [
    {
      district: "Ludhiana",
      bestCrop: "Wheat",
      topCrop1: "Wheat",
      topCrop2: "Paddy",
      topCrop3: "Maize",
      expectedYield: "45 Q/acre",
      marketPrice: "₹2,650/Q",
      profitPerAcre: "₹69,000/acre",
      riskLevel: "Low",
      reason: "Well-aligned with Punjab's wheat belt and strong demand.",
    },
    {
      district: "Amritsar",
      bestCrop: "Wheat",
      topCrop1: "Wheat",
      topCrop2: "Paddy",
      topCrop3: "Maize",
      expectedYield: "46 Q/acre",
      marketPrice: "₹2,700/Q",
      profitPerAcre: "₹71,000/acre",
      riskLevel: "Low",
      reason: "Strong regional suitability and dependable pricing.",
    },
    {
      district: "Patiala",
      bestCrop: "Paddy",
      topCrop1: "Paddy",
      topCrop2: "Wheat",
      topCrop3: "Maize",
      expectedYield: "50 Q/acre",
      marketPrice: "₹2,250/Q",
      profitPerAcre: "₹74,000/acre",
      riskLevel: "Medium",
      reason: "Strong irrigation support and good returns from paddy.",
    },
    {
      district: "Jalandhar",
      bestCrop: "Maize",
      topCrop1: "Maize",
      topCrop2: "Wheat",
      topCrop3: "Paddy",
      expectedYield: "32 Q/acre",
      marketPrice: "₹2,100/Q",
      profitPerAcre: "₹66,000/acre",
      riskLevel: "Low",
      reason: "Suitable for diversified cropping and fodder demand.",
    },
    {
      district: "default",
      bestCrop: "Wheat",
      topCrop1: "Wheat",
      topCrop2: "Paddy",
      topCrop3: "Maize",
      expectedYield: "45 Q/acre",
      marketPrice: "₹2,650/Q",
      profitPerAcre: "₹69,000/acre",
      riskLevel: "Low",
      reason: "State-level fallback recommendation for Punjab.",
    },
  ],
  haryana: [
    {
      district: "Karnal",
      bestCrop: "Wheat",
      topCrop1: "Wheat",
      topCrop2: "Paddy",
      topCrop3: "Mustard",
      expectedYield: "44 Q/acre",
      marketPrice: "₹2,620/Q",
      profitPerAcre: "₹68,000/acre",
      riskLevel: "Low",
      reason: "Strong suitability for the district's agronomic pattern.",
    },
    {
      district: "Hisar",
      bestCrop: "Cotton",
      topCrop1: "Cotton",
      topCrop2: "Wheat",
      topCrop3: "Mustard",
      expectedYield: "29 Q/acre",
      marketPrice: "₹7,000/Q",
      profitPerAcre: "₹86,000/acre",
      riskLevel: "Medium",
      reason: "Favorable for the region and supported by strong demand.",
    },
    {
      district: "Gurugram",
      bestCrop: "Mustard",
      topCrop1: "Mustard",
      topCrop2: "Wheat",
      topCrop3: "Cotton",
      expectedYield: "17 Q/acre",
      marketPrice: "₹5,400/Q",
      profitPerAcre: "₹64,000/acre",
      riskLevel: "Low",
      reason: "Good fit for the region's rabi cropping pattern.",
    },
    {
      district: "Rohtak",
      bestCrop: "Cotton",
      topCrop1: "Cotton",
      topCrop2: "Wheat",
      topCrop3: "Mustard",
      expectedYield: "28 Q/acre",
      marketPrice: "₹6,800/Q",
      profitPerAcre: "₹82,000/acre",
      riskLevel: "Medium",
      reason: "Supports stronger returns with suitable climatic conditions.",
    },
    {
      district: "default",
      bestCrop: "Wheat",
      topCrop1: "Wheat",
      topCrop2: "Mustard",
      topCrop3: "Cotton",
      expectedYield: "44 Q/acre",
      marketPrice: "₹2,620/Q",
      profitPerAcre: "₹68,000/acre",
      riskLevel: "Low",
      reason: "State-level fallback recommendation for Haryana.",
    },
  ],
  gujarat: [
    {
      district: "Ahmedabad",
      bestCrop: "Groundnut",
      topCrop1: "Groundnut",
      topCrop2: "Cotton",
      topCrop3: "Wheat",
      expectedYield: "26 Q/acre",
      marketPrice: "₹6,600/Q",
      profitPerAcre: "₹90,000/acre",
      riskLevel: "Low",
      reason: "Good fit for the climate and strong market demand.",
    },
    {
      district: "Rajkot",
      bestCrop: "Groundnut",
      topCrop1: "Groundnut",
      topCrop2: "Cotton",
      topCrop3: "Bajra",
      expectedYield: "25 Q/acre",
      marketPrice: "₹6,500/Q",
      profitPerAcre: "₹88,000/acre",
      riskLevel: "Medium",
      reason: "Suitable for dryland cropping and resilient returns.",
    },
    {
      district: "default",
      bestCrop: "Groundnut",
      topCrop1: "Groundnut",
      topCrop2: "Cotton",
      topCrop3: "Wheat",
      expectedYield: "26 Q/acre",
      marketPrice: "₹6,600/Q",
      profitPerAcre: "₹90,000/acre",
      riskLevel: "Low",
      reason: "State-level fallback recommendation for Gujarat.",
    },
  ],
  "uttar pradesh": [
    {
      district: "Lucknow",
      bestCrop: "Wheat",
      topCrop1: "Wheat",
      topCrop2: "Sugarcane",
      topCrop3: "Paddy",
      expectedYield: "44 Q/acre",
      marketPrice: "₹2,500/Q",
      profitPerAcre: "₹65,000/acre",
      riskLevel: "Low",
      reason: "Excellent fit for the region's wide wheat cultivation belt.",
    },
    {
      district: "Agra",
      bestCrop: "Sugarcane",
      topCrop1: "Sugarcane",
      topCrop2: "Wheat",
      topCrop3: "Paddy",
      expectedYield: "400 Q/acre",
      marketPrice: "₹320/Q",
      profitPerAcre: "₹1,05,000/acre",
      riskLevel: "Medium",
      reason: "High-value perennial crop with strong local demand.",
    },
    {
      district: "default",
      bestCrop: "Wheat",
      topCrop1: "Wheat",
      topCrop2: "Sugarcane",
      topCrop3: "Paddy",
      expectedYield: "44 Q/acre",
      marketPrice: "₹2,500/Q",
      profitPerAcre: "₹65,000/acre",
      riskLevel: "Low",
      reason: "State-level fallback recommendation for Uttar Pradesh.",
    },
  ],
};

const normalizeText = (value = "") =>
  String(value)
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, " ")
    .trim();

const fallbackRecommendations = {
  "andhra pradesh": {
    bestCrop: "Groundnut",
    topCrop1: "Groundnut",
    topCrop2: "Mango",
    topCrop3: "Cotton",
    expectedYield: "28 Q/acre",
    marketPrice: "₹6,800/Q",
    profitPerAcre: "₹95,000/acre",
    riskLevel: "Low",
    reason: "Default recommendation for Andhra Pradesh.",
  },
  telangana: {
    bestCrop: "Cotton",
    topCrop1: "Cotton",
    topCrop2: "Maize",
    topCrop3: "Red Gram",
    expectedYield: "30 Q/acre",
    marketPrice: "₹7,100/Q",
    profitPerAcre: "₹88,000/acre",
    riskLevel: "Medium",
    reason: "Default recommendation for Telangana.",
  },
  "tamil nadu": {
    bestCrop: "Sugarcane",
    topCrop1: "Sugarcane",
    topCrop2: "Coconut",
    topCrop3: "Banana",
    expectedYield: "420 Q/acre",
    marketPrice: "₹340/Q",
    profitPerAcre: "₹1,15,000/acre",
    riskLevel: "Low",
    reason: "Default recommendation for Tamil Nadu.",
  },
  karnataka: {
    bestCrop: "Maize",
    topCrop1: "Maize",
    topCrop2: "Cotton",
    topCrop3: "Ragi",
    expectedYield: "33 Q/acre",
    marketPrice: "₹2,100/Q",
    profitPerAcre: "₹70,000/acre",
    riskLevel: "Medium",
    reason: "Default recommendation for Karnataka.",
  },
  kerala: {
    bestCrop: "Coconut",
    topCrop1: "Coconut",
    topCrop2: "Rubber",
    topCrop3: "Banana",
    expectedYield: "90 nuts/tree",
    marketPrice: "₹25/nut",
    profitPerAcre: "₹78,000/acre",
    riskLevel: "Low",
    reason: "Default recommendation for Kerala.",
  },
  maharashtra: {
    bestCrop: "Cotton",
    topCrop1: "Cotton",
    topCrop2: "Sugarcane",
    topCrop3: "Soybean",
    expectedYield: "28 Q/acre",
    marketPrice: "₹6,900/Q",
    profitPerAcre: "₹84,000/acre",
    riskLevel: "Medium",
    reason: "Default recommendation for Maharashtra.",
  },
  punjab: {
    bestCrop: "Wheat",
    topCrop1: "Wheat",
    topCrop2: "Paddy",
    topCrop3: "Maize",
    expectedYield: "45 Q/acre",
    marketPrice: "₹2,650/Q",
    profitPerAcre: "₹69,000/acre",
    riskLevel: "Low",
    reason: "Default recommendation for Punjab.",
  },
  haryana: {
    bestCrop: "Wheat",
    topCrop1: "Wheat",
    topCrop2: "Mustard",
    topCrop3: "Cotton",
    expectedYield: "44 Q/acre",
    marketPrice: "₹2,620/Q",
    profitPerAcre: "₹68,000/acre",
    riskLevel: "Low",
    reason: "Default recommendation for Haryana.",
  },
  gujarat: {
    bestCrop: "Groundnut",
    topCrop1: "Groundnut",
    topCrop2: "Cotton",
    topCrop3: "Wheat",
    expectedYield: "26 Q/acre",
    marketPrice: "₹6,600/Q",
    profitPerAcre: "₹90,000/acre",
    riskLevel: "Low",
    reason: "Default recommendation for Gujarat.",
  },
  "uttar pradesh": {
    bestCrop: "Wheat",
    topCrop1: "Wheat",
    topCrop2: "Sugarcane",
    topCrop3: "Paddy",
    expectedYield: "44 Q/acre",
    marketPrice: "₹2,500/Q",
    profitPerAcre: "₹65,000/acre",
    riskLevel: "Low",
    reason: "Default recommendation for Uttar Pradesh.",
  },
};

const cropMeta = {
  Groundnut: { emoji: "🌰", season: "Kharif Season" },
  Arecanut: { emoji: "🌴", season: "Year-round" },
  Coffee: { emoji: "☕", season: "Year-round" },
  Mango: { emoji: "🥭", season: "Seasonal" },
  Tomato: { emoji: "🍅", season: "Rabi Season" },
  Sunflower: { emoji: "🌻", season: "Kharif Season" },
  Cotton: { emoji: "🌿", season: "Kharif Season" },
  Maize: { emoji: "🌽", season: "Kharif Season" },
  "Red Gram": { emoji: "🫘", season: "Kharif Season" },
  Sugarcane: { emoji: "🎋", season: "Year-round" },
  Coconut: { emoji: "🥥", season: "Year-round" },
  Banana: { emoji: "🍌", season: "Year-round" },
  Paddy: { emoji: "🌾", season: "Kharif Season" },
  Ragi: { emoji: "🌾", season: "Kharif Season" },
  Wheat: { emoji: "🌾", season: "Rabi Season" },
  Mustard: { emoji: "🌱", season: "Rabi Season" },
  Rubber: { emoji: "🌿", season: "Year-round" },
  Soybean: { emoji: "🌱", season: "Kharif Season" },
  Bajra: { emoji: "🌾", season: "Kharif Season" },
};

export const getLocationRecommendation = (profile = {}) => {
  const state = normalizeText(profile.state || profile.State || profile.locationState || "");
  const district = normalizeText(profile.district || profile.District || profile.locationDistrict || "");
  const stateRecommendations = cropRecommendationDataset[state];

  if (stateRecommendations) {
    const matchingDistrict = stateRecommendations.find(
      (item) => normalizeText(item.district) === district
    );

    if (matchingDistrict) {
      return {
        ...matchingDistrict,
        state: profile.state || profile.State || "",
        district: profile.district || profile.District || "",
        crop: matchingDistrict.bestCrop,
        yield: matchingDistrict.expectedYield,
        price: matchingDistrict.marketPrice,
        risk: matchingDistrict.riskLevel,
        top3: [matchingDistrict.topCrop1, matchingDistrict.topCrop2, matchingDistrict.topCrop3],
      };
    }

    const stateFallback = fallbackRecommendations[state] || stateRecommendations.find((item) => normalizeText(item.district) === "default");
    if (stateFallback) {
      return {
        ...stateFallback,
        state: profile.state || profile.State || "",
        district: profile.district || profile.District || "",
        crop: stateFallback.bestCrop,
        yield: stateFallback.expectedYield,
        price: stateFallback.marketPrice,
        risk: stateFallback.riskLevel,
        top3: [stateFallback.topCrop1, stateFallback.topCrop2, stateFallback.topCrop3],
      };
    }
  }

  return {
    ...fallbackRecommendations["andhra pradesh"],
    state: profile.state || profile.State || "",
    district: profile.district || profile.District || "",
    crop: fallbackRecommendations["andhra pradesh"].bestCrop,
    yield: fallbackRecommendations["andhra pradesh"].expectedYield,
    price: fallbackRecommendations["andhra pradesh"].marketPrice,
    risk: fallbackRecommendations["andhra pradesh"].riskLevel,
    top3: [
      fallbackRecommendations["andhra pradesh"].topCrop1,
      fallbackRecommendations["andhra pradesh"].topCrop2,
      fallbackRecommendations["andhra pradesh"].topCrop3,
    ],
  };
};

export const getRecommendationCards = (profile = {}) => {
  const recommendation = getLocationRecommendation(profile);
  return recommendation.top3.map((crop, index) => {
    const meta = cropMeta[crop] || { emoji: "🌱", season: "Seasonal" };
    return {
      id: index + 1,
      crop,
      emoji: meta.emoji,
      season: meta.season,
      profitPerAcre: recommendation.profitPerAcre,
      margin: index === 0 ? "58%" : index === 1 ? "52%" : "48%",
      yield: recommendation.yield,
      yieldBadge: index === 0 ? "High" : "Medium",
      price: recommendation.price,
      priceBadge: index === 0 ? "High" : "Medium",
      risk: recommendation.risk,
      riskBadge: recommendation.risk,
      color: index === 0 ? "#FBB040" : index === 1 ? "#9CA3AF" : "#EF4444",
      reason: recommendation.reason,
    };
  });
};

export const getRecommendationInputDefaults = (profile = {}) => {
  const recommendation = getLocationRecommendation(profile);
  const parsedYield = Number(String(recommendation.yield).replace(/[^\d.]/g, ""));
  const parsedPrice = Number(String(recommendation.price).replace(/[^\d.]/g, ""));
  return {
    crop: recommendation.crop,
    yieldPerAcre: Number.isFinite(parsedYield) ? String(parsedYield) : "30",
    pricePerQuintal: Number.isFinite(parsedPrice) ? String(parsedPrice) : "2500",
    risk: recommendation.risk,
    reason: recommendation.reason,
  };
};

export default cropRecommendationDataset;
